[package]
name = "nexus-partition"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.7", features = ["cargo"] }
rayon = "1.*"

[[bin]]
name = "np"
path = "src/main.rs"